language: node_js
branches:
  only:
  - /^v[0-9]+.[0-9]+.[0-9]+$/
node_js:
  - "8"
os:
  - osx
# osx_image: xcode9.1
before_install:
  # - brew update
  - brew reinstall gettext
  - brew unlink gettext && brew link gettext --force
install:
  - npm install

script:
  - rm -rf electron-resources/license*
  - npm run publish-ml
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GH_TOKEN
#   on:
#     tags: true