language: node_js
branches:
  only:
  - master
  - /^v[0-9]+.[0-9]+.[0-9]+$/
node_js:
  - "8"
os:
  - osx
osx_image: xcode9.1
before_install:
  # - brew update
  - brew reinstall gettext
  - brew unlink gettext && brew link gettext --force
install:
  - sudo npm i -g cordova
  - sudo npm i -g ionic
  - npm install

script:
  - rm -rf electron/electron-resources/license*
  - chmod +x macos-signing.sh
  - ./macos-signing.sh
  - npm run publish