language: node_js
os:
  - osx

install:
  - npm install

script:
  - npm run publish-m

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master