version: 1.0.{build}
environment:
  nodejs_version: "8"
branches:
  only:
  - master
init:

install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install
build:
  - cmd: npm run dist
  verbosity: minimal