version: 1.0.{build}
environment:
  nodejs_version: "8"
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'
branches:
  only:
  - master
image: Visual Studio 2015
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - appveyor DownloadFile https://github.com/fttx/barcode-to-pc-server/blob/master/electron-resources/Bonjour64.msi?raw=true
  - msiexec /i Bonjour64.msi /qn
  - del Bonjour64.msi
  - appveyor DownloadFile https://barcodetopc.com/download/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.4;%path%
  - set path=%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%path%
  - set ECHO=ON 
  - echo "%path%"
  - echo "%NODE_ENV%"
  - set NODE_ENV=production
  - npm run tsc --version
  - npm install

  

build_script:
  - npm run dist
build:  
  verbosity: minimal