version: 1.0.{build}
environment:
  nodejs_version: "8"
branches:
  only:
  - master
install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install
build_script:
  - cmd: npm run dist
build:  
  verbosity: minimal