version: 1.0.{build}
environment:
  nodejs_version: "8"
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'
branches:
  only:
  - master
image: Visual Studio 2015
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.4;%PATH%
 
 
  - appveyor DownloadFile https://github.com/fttx/barcode-to-pc-server/blob/master/electron-resources/Bonjour64.msi?raw=true
  - msiexec /i Bonjour64.msi /qn
  - del Bonjour64.msi
  - appveyor DownloadFile https://barcodetopc.com/download/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe

  - set NODE_ENV=production  
  - npm install

  - set PATH=%APPDATA%\npm;%PATH%
  - set PATH=%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - set ECHO=ON 
  - echo "%PATH%"
  - echo "%NODE_ENV%"
  - node --version
  - npm --version
  - npm run tsc --version

  

build_script:
  - npm run dist
build:  
  verbosity: minimal