version: 1.0.{build}
environment:
  nodejs_version: "6"
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'
branches:
  only:
  - master
image: Visual Studio 2015
install:
  - ps: Install-Product node $env:nodejs_version
  set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.2;%path%
  - node --version
  - npm --version
  - appveyor DownloadFile https://github.com/fttx/barcode-to-pc-server/blob/master/electron-resources/Bonjour64.msi?raw=true
  - msiexec /i Bonjour64.msi /qn
  - del Bonjour64.msi
  - appveyor DownloadFile https://barcodetopc.com/download/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  - npm install 
  - npm install --no-save typescript@2.5
  - echo %NODE_ENV%  
  - npm run tsc --version

build_script:
  - npm run dist
build:  
  verbosity: minimal