version: v{build} # doesn't matter because gets overwritten later on with the package.json value
branches:
  only:
    - master
skip_non_tags: false
clone_depth: 1
environment:
  nodejs_version: "8"
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'
  BONJOUR_SDK_DOWNLOAD:
    secure: 1uWToJLKf6uUn0/fsVHbrRSHDDgyxJ9KgD4cslGCqmz486RoS5levXRMLCKm3E7flrnyhSXcUWFHK9KcUxPlO2LYHYRVR+OGkndJ0fbrxhY=
image: Visual Studio 2015
install:
  - ps: Install-Product node $env:nodejs_version x64
  - ps: npm install -g npm@6.11.3
  - set PATH=%programfiles(x86)%\\Microsoft SDKs\TypeScript\2.4;%PATH%

  - appveyor DownloadFile https://github.com/fttx/barcode-to-pc-server/blob/master/electron/electron-resources/Bonjour64.msi?raw=true
  - msiexec /i Bonjour64.msi /qn
  - del Bonjour64.msi
  - appveyor DownloadFile %BONJOUR_SDK_DOWNLOAD%
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe

  - git config --global user.email "filippo.tortomasi@gmail.com"
  - git config --global user.name "Filippo Tortomasi"

  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version # extract the version from package.json
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER" # use the package.json version

  - npm cache verify
  - npm ci --unsafe-perm
  - cd ionic
  - npm ci --unsafe-perm
  - cd ..
  - set NODE_ENV=production
  - set ECHO=ON
  - echo "%PATH%"
  - echo "%NODE_ENV%"
  - node --version
  - npm --version
  - npm run tsc --version
build_script:
  # Remove certificateSha1 from package.json to avoid build error
  - ps: $package_json = Get-Content -Raw -Path .\package.json
  - ps: $package_json = $package_json -replace ".*certificateSha1.*\r?\n" -replace ",(?=\r?\n\W+})"
  - ps: echo $package_json
  - ps: '[System.IO.File]::WriteAllLines(".\package.json", $package_json)' # save the file as UTF-8 with no BOM
  - ps: $package_json = Get-Content -Raw -Path .\package.json
  - ps: echo $package_json
  - cmd: npm run dist
artifacts:
  - path: \dist\dist\nsis-web
    name: barcode-to-pc-server.$env:package_version-$env:APPVEYOR_BUILD_NUMBER.offline-installer
    type: zip
test: off
