version: 1.0.{build}
environment:
  nodejs_version: "8"
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'
branches:
  only:
  - master
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjourcore2.msi
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - appveyor DownloadFile https://www.samuelattard.com/files/bonjoursdksetup.exe
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  - cmd: npm install 

build_script:
  - cmd: npm run dist
build:  
  verbosity: minimal